### ISSUE TITLE
Icon sizes are not consistent

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-apps#1]
```
Emiliano Villegas Trejo to quang

Good day,
I know it's only aesthetic but the size of some icons is too big and it looks weird along with other applications on Mac in the app launcher and the dock. An example is the Google Keep icon.

Just a small suggestion, thank you.
```

@ianjukes Can you help with this, please :)?

**Comment by jlandes** [comment]
@quanglam2807 Can we come up with a consistent icon size and program that in when a new app is added, so it checks the size of the icon and adjusts if necessary?

**Comment by quanglam2807** [comment]
@jlandes It would be a difficult task. Also, which guideline of icons should we follow?

**Comment by jlandes** [comment]
@quanglam2807 Do we need icons larger than 256x256? If not, couldn’t we make them all that size and code a resize function for any icons larger than that so it would decrease their size when the app is added?

**Comment by quanglam2807** [comment]
The image sizes are not the problem. No matter if you upload a 256x256 or a 1024x1024 or a 257x257, it is then automatically resized and compiled by the system. 

Icons are inconsistent because the real sizes of the icons inside the image are different. You can have an image in 1024x1024px but it only has a 1px sprite inside it then that one should be rejected.

**Comment by jlandes** [comment]
@quanglam2807 That makes sense to me.

**Comment by VirgileACM** [comment]
Hey @quanglam2807, congrats on web-catalog, it's a very useful and beautiful piece of software! 
I like it enough that I decided to contribute after posting [here](https://github.com/webcatalog/webcatalog-apps/issues/11) and seeing this issue.

Basically, I wrote a python script that finds icons' borders by using their transparencies, and then center, resize and pad them according to some parameters (here output image of 512x512 and 20px pad). Also, drop shadows are kept but not taken into account for centering and scaling to look more natural. This should be enough to bring consistency to the icons sizes, similarly to the 'normalize icon size' feature in Nova Launcher if you use Android.

I run it on the 484 apps and it took about 8mins, so it's not optimized but I doubt it would be a real bottleneck to wait roughly 1s for formatting an icon. Regarding the control and reject of some icons that have low resolution, I was thinking of printing warnings or stopping the run when the ratio for resizing is, for instance, higher than 1.5, it would be easy to add but it depends on how you run your code in js (which I didn't look into). 

I will fork and commit it later in the day. I put here some output samples to compare (left is original and right is formatted, pink represents transparency):

Air-table for downsizing to padding:
![airtable-icon](https://user-images.githubusercontent.com/16863520/34261259-dfc1042c-e668-11e7-83b6-b87ffe1439e7.png)
Alto-mail upsizing to padding:
![alto-mail-icon](https://user-images.githubusercontent.com/16863520/34261278-f1bbe69c-e668-11e7-9dbb-f3192fdeeb94.png)
Behance for icons fitted to borders:
![behance-icon](https://user-images.githubusercontent.com/16863520/34261359-3bfcc2bc-e669-11e7-8b99-d8b5771b089b.png)
Dribble for icons with large drop shadow:
![dribbble-icon](https://user-images.githubusercontent.com/16863520/34261437-69f54446-e669-11e7-8b30-bea66fc230af.png)
Google Maps is centered as well, I find that consistent padding is better than padding on squared part of icon:
![google-maps-icon](https://user-images.githubusercontent.com/16863520/34261590-de139a4e-e669-11e7-8746-015d8d7d9112.png)
YouTube gaming for centering:
![youtube-gaming-icon](https://user-images.githubusercontent.com/16863520/34261703-571d15aa-e66a-11e7-9eed-428a99b330e7.png)

**Comment by quanglam2807** [comment]
@VirgileACM Thanks a lot for helping! I really appreciate! I don't know much about this stuff so without you, I would never be able to resolve this issue. The icons look excellent and I have nothing to complain. I'm looking forward to your PR 👍.

---

Also, just to save your time:
The code which generates the icon files: https://github.com/webcatalog/webcatalog-apps/blob/master/script/pack.js#L28

The code which tests the data: https://github.com/webcatalog/webcatalog-apps/blob/master/test/human-data.js

I created this repo based on https://github.com/electron/electron-apps so you can also reference it. The original one tests both `human-data` and `machine-data` (https://github.com/electron/electron-apps/blob/master/test/machine-data.js) but currently, I only test the `human-data` in this repo. 

---

Also, 8 minutes are not really a big deal. We can optimize it later by splitting it into multiple processes.

**Comment by VirgileACM** [comment]
@quanglam2807 You are welcome, glad I can help! 👍 Let me know if you took a look at the branch I updated with the python script.

Also, I am not familiar at all with developing Electron applications nor have the time to get into it at the moment. If you tell me how you need the python script to be changed in order to fit in your pipeline, I can do it easily, but unfortunately, I won't be able to insert it myself.

As I am not clear on the process for adding apps, I am not clear either on how to modify supported apps. Can we directly update the already supported apps? Does running the script in the apps folder and updating all the .png will automatically update the apps? The script is already able to do that. If not at which level do we need to insert the script?

Concerning the file that generates icons, I see that you save the raw icon-file in this repository and then make a 128x128px icon that you save in another location. How should we format both?
I can modify the python script to fit in packs.js if you tell me what is the input you give me inside and what output do you need. Then I imagine you can insert a piece of js in pack.js that runs the python script.

**Comment by quanglam2807** [comment]
@VirgileACM I should have written better documentation. But here's how it works:

First, you run `yarn build:pack`. The script will run, use the data in `apps` folder (`human-data`) and generate a `dist` folder (`machine-data`).

Then, `yarn build:publish` will upload `dist` folder to S3 & Algolia and overwrite the old metadata & icons. (It's handled by CI).

So we have 2 options:
- You run the Python script after `yarn build:pack` and modify all the icons in the `dist` folder.
- You create a Python script which takes an icon path as input `fix.py ./icon.png` and then overwrite it with a corrected one.

**Comment by VirgileACM** [comment]
@quanglam2807 Thanks, I see now 👍 
The second option seems indeed more natural. I will try to do that today and add modularity to your suggestion to customize on the fly the output size and padding.

**Comment by VirgileACM** [comment]
Added PR #13.
