### ISSUE TITLE
App Request: Nuclino

### ISSUE THREAD

**Issue by navedcoded** [webcatalog/webcatalog-apps#8]
Name: Nuclino
URL: https://app.nuclino.com
Icon: https://pbs.twimg.com/profile_images/668746110182301698/0eu6N48V.png

(I couldn't find if I could add this on my own and make a pull request. Is the app catalog server side?)

**Comment by quanglam2807** [comment]
@navedcoded Thanks a lot. You can make PR and I'll merge it. This is the instruction: https://github.com/webcatalog/webcatalog-apps/blob/master/CONTRIBUTING.md.

The system will automatically publish the apps to Algolia.

**Comment by jlandes** [comment]
I went ahead and added this and submitted the PR.

**Comment by quanglam2807** [comment]
@jlandes Awesome! Thanks a lot.
